### Exercise 1:NumPy array Indexing Slicing

#### 1.1. In this exercise , we will use the iris dataset . Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).

In [9]:
import sys
sys.path.append('/home/pauloseixal/Github/si')

from src.si.io.csv_file import read_csv
import numpy as np

iris = read_csv('../datasets/iris/iris.csv', features=True, label=True)
iris.summary()


sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

#### 1.2. Select the penultimate independent variable . What is the dimension of the resulting array

In [10]:
dim = iris.X[:,-2].shape[0]
print(f'Dimension: {dim}')

Dimension: 150


#### 1.3. Select the last 10 samples from the iris dataset . What is the mean of the last 10 samples for each independent variable feature

In [11]:
np.nanmean(iris.X[-10:], axis=0)

array([6.45, 3.03, 5.33, 2.17])

#### 1.4. Select all samples from the dataset with values less than or equal to 6 for all independent variables features . How many samples do you obtain

In [12]:
select = np.all(iris.X <= 6, axis=1)
select_samples = iris.X[select]

print(f'Obtained samples: {select_samples.shape[0]}')

Obtained samples: 89


#### 1.5. Select all samples with a class label different from 'Iris setosa '. How many samples do you obtain

In [13]:
selected_samples = iris.X[(iris.y != 'Iris-setosa')].shape[0]

print(f'Obtained samples: {selected_samples}')

Obtained samples: 100


### Exercise 2: (Optional) examples of how to use the new methods 

```dropna```

In [17]:
from src.si.data.dataset import Dataset

X = np.array([[1, 2, 3], [4, 5, 6], [6, 7, np.nan]])
y = np.array([1, 2, 3])
features = np.array(['a', 'b', 'c'])
label = 'y'
dataset = Dataset(X, y, features, label)

print(dataset.X)
print()
dataset.dropna()
print(dataset.X)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 6.  7. nan]]

[[1. 2. 3.]
 [4. 5. 6.]]


```fillna```

In [21]:
X = np.array([[1, 2, 3], [4, 5, 6], [6, 7, np.nan]])
y = np.array([1, 2, 3])
features = np.array(['a', 'b', 'c'])
label = 'y'
dataset = Dataset(X, y, features, label)

# print(dataset.X)
# print()
# dataset.fillna(1)
# print(dataset.X)

# print(dataset.X)
# print()
# dataset.fillna('median')
# print(dataset.X)

print(dataset.X)
print()
dataset.fillna('mean')
print(dataset.X)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 6.  7. nan]]

[[1.  2.  3. ]
 [4.  5.  6. ]
 [6.  7.  4.5]]


```remove_by_index```

In [23]:
X = np.array([[1, 2, 3], [4, 5, 6], [6, 7, np.nan]])
y = np.array([1, 2, 3])
features = np.array(['a', 'b', 'c'])
label = 'y'
dataset = Dataset(X, y, features, label)

print(dataset.X)
print()
dataset.remove_by_index(1)
print(dataset.X)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 6.  7. nan]]

[[ 1.  2.  3.]
 [ 6.  7. nan]]
