### Testing one-hot encoding

In [1]:
from si.encoding.one_hot_encoder import OneHotEncoder
import numpy as np

# example data
data = np.array(['abc', 'def', 'ab', 'de'])

# encoder
custom_encoder = OneHotEncoder(padder='_')
custom_encoded = custom_encoder.fit_transform(data)
custom_decoded = custom_encoder.inverse_transform(custom_encoded)

# comparing results
print("Categories:\n", custom_encoder.alphabet)
print("Custom Encoder Encoded:\n", custom_encoded)
print("Custom Encoder Decoded:\n", custom_decoded)

Categories:
 ['a' 'b' 'c' 'd' 'e' 'f' '_']
Custom Encoder Encoded:
 [[[1. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]]

 [[1. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]

 [[0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]
Custom Encoder Decoded:
 ['abc', 'def', 'ab', 'de']
