In [3]:
import numpy as np

### Exercise 2: (Optional) examples of how to use the new methods 

```dropna```

In [4]:
from si.data.dataset import Dataset

X = np.array([[1, 2, 3], [4, 5, 6], [6, 7, np.nan]])
y = np.array([1, 2, 3])
features = np.array(['a', 'b', 'c'])
label = 'y'
dataset = Dataset(X, y, features, label)

print(dataset.X)
print()
dataset.dropna()
print(dataset.X)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 6.  7. nan]]

[[1. 2. 3.]
 [4. 5. 6.]]


```fillna```

In [5]:
X = np.array([[1, 2, 3], [4, 5, 6], [6, 7, np.nan]])
y = np.array([1, 2, 3])
features = np.array(['a', 'b', 'c'])
label = 'y'
dataset = Dataset(X, y, features, label)

# print(dataset.X)
# print()
# dataset.fillna(1)
# print(dataset.X)

# print(dataset.X)
# print()
# dataset.fillna('median')
# print(dataset.X)

print(dataset.X)
print()
dataset.fillna('mean')
print(dataset.X)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 6.  7. nan]]

[[1.  2.  3. ]
 [4.  5.  6. ]
 [6.  7.  4.5]]


```remove_by_index```

In [6]:
X = np.array([[1, 2, 3], [4, 5, 6], [6, 7, np.nan]])
y = np.array([1, 2, 3])
features = np.array(['a', 'b', 'c'])
label = 'y'
dataset = Dataset(X, y, features, label)

print(dataset.X)
print()
dataset.remove_by_index(1)
print(dataset.X)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 6.  7. nan]]

[[ 1.  2.  3.]
 [ 6.  7. nan]]
