### Exercise 4: Manhattan distance

In [36]:
from si.statistics.manhattan_distance import manhattan_distance
import numpy as np

x = np.array([1, 2, 3])
y = np.array([[4, 5, 6], [7, 8, 9]])
md = manhattan_distance(x, y)

# using sklearn
from sklearn.metrics.pairwise import manhattan_distances
sklearn_md = manhattan_distances([x], y)


print("Our Manhattan distance:", md)
print("Sklearn Manhattan distance:", sklearn_md)

Our Manhattan distance: [ 9 18]
Sklearn Manhattan distance: [[ 9. 18.]]


### Exercise 5: PCA

In [34]:
from si.io.csv_file import read_csv
from si.decomposition.pca import PCA
iris = read_csv('/home/pauloseixal/Github/si/datasets/iris/iris.csv',sep=',',features=True, label=True)

#float n_components
pca = PCA(n_components=0.95)
pca.fit_transform(iris)
print('float (0.95) n_components:')
print('components:', pca.components)
print('explained variance:', pca.explained_variance)
print('explained variance ratio:',pca.explained_variance_ratio)
print()

#int n_components
pca = PCA(n_components=2)
pca.fit_transform(iris)
print('int (2) n_components:')
print('components:', pca.components)
print('explained variance:', pca.explained_variance)
print('explained variance ratio:', pca.explained_variance_ratio)




float (0.95) n_components:
components: [[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [-0.65653988 -0.72971237  0.1757674   0.07470647]]
explained variance: [4.22484077 0.24224357]
explained variance ratio: [0.94577144 0.05422856]

int (2) n_components:
components: [[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [-0.65653988 -0.72971237  0.1757674   0.07470647]]
explained variance: [4.22484077 0.24224357]
explained variance ratio: [0.94577144 0.05422856]


In [21]:
pca.mean

array([5.84333333, 3.054     , 3.75866667, 1.19866667])